// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSepd6UrxpWF1fb4BiRNGTKEVKv9d9csY',
    appId: '1:773575950174:web:e17d4e84f3f54582b059cf',
    messagingSenderId: '773575950174',
    projectId: 'teste-action-efe10',
    authDomain: 'teste-action-efe10.firebaseapp.com',
    databaseURL: 'https://teste-action-efe10.firebaseio.com',
    storageBucket: 'teste-action-efe10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgDYEmFOL4yLC9Q7xRley9f5dpnnYkFM',
    appId: '1:773575950174:android:ee78fa75b0bf2b10b059cf',
    messagingSenderId: '773575950174',
    projectId: 'teste-action-efe10',
    databaseURL: 'https://teste-action-efe10.firebaseio.com',
    storageBucket: 'teste-action-efe10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlWmuzr85b-YFwQVNChQ08MciPqPehrS8',
    appId: '1:773575950174:ios:fc0f55f898f88233b059cf',
    messagingSenderId: '773575950174',
    projectId: 'teste-action-efe10',
    databaseURL: 'https://teste-action-efe10.firebaseio.com',
    storageBucket: 'teste-action-efe10.firebasestorage.app',
    iosBundleId: 'com.cfgdemelo.bpb',
  );
}
